import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ScrollAnimation from "./components/ScrollAnimation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Regent Degitect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="overflow-clip">
        
           <div className="z-20 sticky top-[-130px] sm:top-[-100px] md:top-[-70px]">
            <Header />
          </div>
          {children} 
          <Footer />
        </div>
      </body>
    </html>
  );
}
